---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-16.04
  run_list:
  - recipe[apt]
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: debian-8.6
- name: debian-7.11
- name: centos-7.2-1511
- name: centos-7.1-1503
- name: centos-6.8

suites:
- name: stock_system_and_user
  run_list:
  - recipe[user::data_bag]
  - recipe[rvm::system]
  - recipe[rvm::user]
  attributes:
    users:
    - wigglebottom
    rvm:
      user_installs:
      - user: wigglebottom
        default_ruby: 2.3.1
- name: rubies
  run_list:
  - recipe[java]
  - recipe[rvm::system]
  attributes:
    rvm:
      default_ruby: system
      rubies:
      - 2.3.1
      - jruby
- name: rbx
  run_list:
  - recipe[rvm::system]
  attributes:
    rvm:
      default_ruby: rbx
- name: installs
  run_list:
  - recipe[user::data_bag]
  - recipe[rvm::user_install]
  attributes:
    users:
    - virgil1
    - virgil2
    rvm:
      installs:
        virgil1:
          installer_flags: --version 1.24.0
        virgil2:
          installer_flags: --version 1.27.0
